### ISSUE TITLE
shapes.monkey - CollidesWith() - Array index out of range.

### ISSUE THREAD

**Issue by RichardBetson** [ratkingsminion/hc-monkey#1]
Hi,

While compiling in 'debug' I get an "Array index out of range" error on line number 436.
Method: CollidesWith() - (If collData.Length() > 0 Then Return[ - collData[1], -collData[2]])

**Comment by ratkingsminion** [comment]
Oops! Just made a commit that should fix it! Please tell me if it does.

https://github.com/ratkingsminion/hc-monkey/commit/0988a99e6b2fe82957e0607ec80bb18230d709f1

**Comment by RichardBetson** [comment]
Looks like that got it fixed. :+1:  Thanks.
